#!/usr/bin/python

import os, sys, subprocess

def usage():
   print "Usage: git-multi-rebase [options] <newbase> <branch0> [<branch1> ... <branchN>]"

if len(sys.argv) < 3:
   usage()
   sys.exit("Wrong number of inputs")

upstream = ""
flags = ['--quiet']
flag_cnt = 1
branches = {}
branch_cnt = 0

for i in range (1, len(sys.argv)):
   arg = sys.argv[i].strip()
   # save flags to pass to git-rebase
   if arg.startswith('-'):
      flags.append(arg)
      flag_cnt += 1
   # save new upstream base
   elif upstream == "":
      upstream = arg
   # save branches to be rebased
   else:
      branches[branch_cnt] = arg
      branch_cnt += 1

if upstream == "":
   usage()
   sys.exit("<newbase> not specified");

if branch_cnt == 0:
   usage()
   sys.exit("no branches specified");


# get the current branch
proc = subprocess.Popen(['git', 'symbolic-ref', '-q', 'HEAD'],
                        stdout=subprocess.PIPE)
proc.wait()
current_branch = proc.stdout.read().split('/')[2].strip()

for i in range(0, branch_cnt):
   print 'rebasing ' + branches[i] + ' onto ' + upstream
   args = ['git', 'rebase'] #, upstream, branches[i]]
   args = args + flags
   args.append(upstream)
   args.append(branches[i])
   proc = subprocess.Popen(args, stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
   rc = proc.wait()
   if rc != 0:
      print proc.stdout
      print "git-multi-rebase: call 'git rebase --continue|--abort' to finish rebasing branch " + branches[i]
      print "git-multi-rebase: exit shell to continue the multi-rebase process"
      subprocess.call(['$SHELL'], shell=True)


# checkout previous branch
if current_branch != branches[branch_cnt-1]:
   subprocess.call(["git", "checkout", current_branch])



