#!/usr/bin/python

import os, sys, subprocess, git_python

def usage():
   print "Usage: git-multi-rebase [options] <newbase> <branch0> [<branch1> ... <branchN>]"

if len(sys.argv) < 3:
   usage()
   sys.exit("Wrong number of inputs")

upstream = ""
flags = ['--quiet']
flag_cnt = 1
branches = {}
branch_cnt = 0

for i in range (1, len(sys.argv)):
   arg = sys.argv[i].strip()
   # save flags to pass to git-rebase
   if arg.startswith('-'):
      flags.append(arg)
      flag_cnt += 1
   # save new upstream base
   elif upstream == "":
      upstream = arg
   # save branches to be rebased
   else:
      branches[branch_cnt] = arg
      branch_cnt += 1

if upstream == "":
   usage()
   sys.exit("<newbase> not specified");

if branch_cnt == 0:
   usage()
   sys.exit("no branches specified");


# get the current branch
current_branch = git_python.cur_branch()

for i in range(0, branch_cnt):
   print 'rebasing ' + branches[i] + ' onto ' + upstream
   git_python.rebase(upstream, branches[i], flags)

# checkout previous branch
if current_branch != branches[branch_cnt-1]:
   subprocess.call(["git", "checkout", current_branch])



